version: '3.6'
services:
  neo4j:
    image: neo4j:5.6.0-community
    restart: unless-stopped
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - ./conf:/conf
      - ./import:/import
      - ./plugins:/plugins
      - ./logs:/logs
      - ./data:/data
    environment: 
      # Raise memory limits
      - NEO4J_AUTH=neo4j/password
      - NEO4J_dbms_memory_pagecache_size=1G
      - NEO4J_dbms.memory.heap.initial_size=1G
      - NEO4J_dbms_memory_heap_max__size=1G
      - NEO4J_dbms.security.allow_csv_import_from_file_urls=true
      - NEO4J_dbms.memory.transaction.total.max=1G
    user: $CURRENT_UID